name: Vector Store Sync

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".docucat/**" # Ignore changes to the vector store itself to prevent infinite loops

jobs:
  update-vector-store:
    runs-on: ubuntu-latest
    name: Initialize or Update Vector Store

    # Required permissions to commit and push
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for git operations
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      - name: Checkout DocuCat
        uses: actions/checkout@v4
        with:
          repository: shuangxuetwelve/docu-cat # Update this to match your DocuCat repository
          path: docu-cat
          # ref: main  # Optionally specify a version/tag

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DocuCat dependencies
        shell: bash
        run: cd docu-cat && uv sync

      - name: Initialize or Update Vector Store
        shell: bash
        run: uv run --directory docu-cat python init_update_store_aga.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_WORKSPACE: ${{ github.workspace }}/target-repo
